apiVersion: batch/v1
kind: CronJob
metadata:
  name: '{{ include "app.fullname" . }}-cron'
spec:
  schedule: "{{ .Values.cron.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["echo", "Hello from CronJob"]
          restartPolicy: OnFailure
