apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-job
spec:
  template:
    spec:
      containers:
        - name: job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["echo", "Hello from Job"]
      restartPolicy: Never
