apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    app: {{ include "grafana.name" . }}
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: {{ include "grafana.name" . }}
  ports:
    - port: {{ .Values.grafana.service.ports.port }}
      targetPort: {{ .Values.grafana.service.ports.targetPort }}
      protocol: {{ .Values.grafana.service.ports.protocol }}
      name: {{ .Values.grafana.service.ports.name }}