apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mongodb.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongodb.name" . }}
    spec:
      containers:
      - name: {{ include "mongodb.name" . }}
        image: {{ .Values.image.name }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "mongodb.name" . }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
