
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "prometheus.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "prometheus.fullname" . }}
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image }}
          args:
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Values.prometheus.config.name }}
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: {{ .Values.prometheus.persistence.name }}
---
{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
        - name: kube-state-metrics
          image: {{ .Values.kubeStateMetrics.image }}
          ports:
            - containerPort: {{ .Values.kubeStateMetrics.port }}
{{- end }}
