apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    app: {{ include "prometheus.fullname" . }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: {{ include "prometheus.fullname" . }}
  ports:
    - port: {{ .Values.prometheus.service.ports.port }}
      targetPort: {{ .Values.prometheus.service.ports.targetPort }}
      protocol: {{ .Values.prometheus.service.ports.protocol }}
      name: {{ .Values.prometheus.service.ports.name }}
---
{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  ports:
    - port: {{ .Values.kubeStateMetrics.service.port }}
      targetPort: {{ .Values.kubeStateMetrics.service.targetPort }}
      name: {{ .Values.kubeStateMetrics.service.portName }}
  selector:
    app: kube-state-metrics
{{- end }}